Repository scp756-221/term-project-data_affair, pull requests merged in 2022-03, with the labels that each got.

#19 updating get_transaction() API endpoint
  s3/app.py
Labels: enhancement

#20 hna37/Update Transaction
  s3/app.py
Labels: enhancement

#21 Added purchases table to dynamodb creation template
  cluster/cloudformationdynamodb-tpl.json
  k8s.mak
  s2/standalone/README.md
Labels: enhancement

#22 Added fetch by key for DB service
  db/app-tpl.py
Labels: enhancement

#27 Modify Loader for data to purchase table and close #23
  gatling/resources/purchases.csv
  loader/app.py
Labels: enhancement

#29 Added get purchase by user id
  s3/app.py
Labels: enhancement

#39 Added pytest testcases for purchase microservice
  ci/v1.1/compose-tpl.yaml
  ci/v1.1/conftest.py
  ci/v1.1/create_tables.py
  ci/v1.1/flake-dirs.txt
  ci/v1.1/purchase.py
  ci/v1.1/test_purchase.py
Labels: enhancement, good first issue

#41 updated get_purchase_testcase as part of #35
  ci/v1.1/test_purchase.py
  ci/v1.1/user.py
Labels: bug

#42 Added testcase for update_purchase_amount and edited condition checks
  ci/v1.1/purchase.py
  ci/v1.1/test_purchase.py
Labels: enhancement

#47 Add test case for create purchase api
  ci/v1.1/test_purchase.py
Labels: enhancement
