Repository scp756-221/term-project-data_affair, pull requests merged in 2022-04, with the labels that each got.

#51 fixing secondary index bug in cloudformation tpl file
  cluster/cloudformationdynamodb-tpl.json
Labels: bug

#53 Update requirements
  db/requirements.txt
  loader/requirements.txt
Labels: bug

#55 Timestamp name change and update purchase parameter removed
  ci/v1.1/purchase.py
  s3/app.py
Labels: bug

#57 Updating timestamp field in loader/app.py
  loader/app.py
Labels: bug

#59 Fixing the big on updating purchase API with changes in s3/app.py and…
  cluster/cloudformationdynamodb-tpl.json
  s3/app.py
Labels: bug

#60 Initial purchase API hit
  gatling/simulations/proj756/ReadTables.scala
Labels: enhancement

#61 Added gatling script
  tools/gatling-1-music.sh
Labels: enhancement

#63 Added Integration test in Purchase API Tests
  ci/v1.1/test_purchase.py
Labels: enhancement

#68 updating ghcr repository location to scp756-221
  cluster/purchases-header.yaml
  cluster/tpl-vars-blank.txt
  k8s-tpl.mak
  k8s.mak
  tools/call-sed.sh
  tools/process-templates.sh
Labels: enhancement

#66 Added coverage for Purchase APIs
  gatling/simulations/proj756/ReadTables.scala
Labels: enhancement

#70 updating yaml files
  cluster/db-nohealth-tpl.yaml
  cluster/db-tpl.yaml
  cluster/loader-tpl.yaml
  cluster/s1-nohealth-tpl.yaml
  cluster/s1-tpl.yaml
  cluster/s2-dpl-v1-tpl.yaml
  cluster/s2-dpl-v2-tpl.yaml
  cluster/s2-nohealth-tpl.yaml
  cluster/s3-nohealth-tpl.yaml
  cluster/s3-tpl.yaml
Labels: bug

#69 Nra38/gatling coverage
  Makefile-tpl.mak
  gatling/resources/load.csv
  gatling/simulations/proj756/ReadTables.scala
  tools/gatling.sh
Labels: enhancement

#73 Added v1 and v2 for Purchase service
  cluster/s3-dpl-v1-tpl.yaml
  cluster/s3-dpl-v2-tpl.yaml
  cluster/s3-svc.yaml
  cluster/s3-vs-canary.yaml
  k8s.mak
  s3/v1/.gitignore
  s3/v1/Dockerfile
  s3/v1/app.py
  s3/v1/requirements.txt
  s3/v2/.gitignore
  s3/v2/Dockerfile
  s3/v2/app.py
  s3/v2/requirements.txt
Labels: enhancement

#74 Added v1 v2 to k8s.mak
  k8s-tpl.mak
  k8s.mak
Labels: bug

#76 loader changes
  cluster/loader-tpl.yaml
  cluster/purchases-header.yaml
  k8s-tpl.mak
  k8s.mak
  loader/app.py
Labels: enhancement

#78 Clean up unused files and maintain script for simulations
  gatling-tpl.mak
  gatling/simulations/proj756/ReadTables.scala
  tools/gatling-1-music.sh
  tools/gatling.sh
Labels: bug

#79 Fixed flak8 conformance errors for db and s3/v1
  ci/v1.1/create_tables.py
  ci/v1.1/purchase.py
  ci/v1.1/user.py
  db/app-tpl.py
  s3/v1/app.py
  s3/v2/app.py
Labels: bug

#80 Cleaned up files. Added v1 for test
  .gitignore
  ci/v1.1/Dockerfile
  ci/v1.1/a7_other_dev_music.py
  ci/v1.1/a7_test_music.py
  ci/v1.1/flake-dirs.txt
  ci/v1.1/music.py
  ci/v1.1/test_music.py
  ci/v1/.gitignore
  ci/v1/Dockerfile
  ci/v1/README.md
  ci/v1/compose-tpl.yaml
  ci/v1/conftest.py
  ci/v1/create_tables.py
  ci/v1/flake-dirs.txt
  ci/v1/music.py
  ci/v1/purchase.py
  ci/v1/requirements.txt
  ci/v1/test_music.py
  ci/v1/test_purchase.py
  ci/v1/user.py
  s2/v1/app.py
Labels: bug

#83 Added s3 to grafana
  cluster/grafana-flask-configmap.yaml
Labels: enhancement

#86 Nra38/gcp infra
  ci/create-local-tables-tpl.sh
  ci/v1/create_tables.py
  ci/v1/purchase.py
  ci/v1/test_purchase.py
  cluster/grafana-flask-configmap.yaml
  gatling/simulations/proj756/ReadTables.scala
  gcp-tpl.mak
  s2/v1/Dockerfile
  s2/v1/unique_code-tpl.py
  tools/process-templates.sh
Labels: bug, enhancement

#87 Separated vs files for S2 and S2 and added yaml for istio delay
  cluster/db-vs-delay.yaml
  cluster/s2-vs-v1.yaml
  cluster/s2-vs-v2.yaml
  cluster/s3-vs-circuitbreaker.yaml
  cluster/s3-vs-delay.yaml
  cluster/s3-vs-v1.yaml
  cluster/s3-vs-v2.yaml
  k8s-tpl.mak
  s3/v2/app.py
Labels: bug, enhancement

#88 Project Directory Cleanup
  allclouds-tpl.mak
  allclouds.mak
  cluster/Kiali-sample-graph.png
  cluster/eks-admin-service-account.yaml
  eks-tpl.mak
  eks.mak
  gatling/simulations/proj756/BasicSimulation.scala
  gcloud/.gitignore
  gcloud/Dockerfile
  gcloud/README.md
  gcloud/gcloud-build-tpl.sh
  gcloud/shell-tpl.sh
  reference/README.md
  reference/istio-profile-default-reference.yaml
  reference/istio-profile-demo-reference.yaml
  reference/kube-prometheus-stack-values-reference.yaml
  reference/prometheus-rules-reference.yaml
  tools/find-canonical-owner.sh
  tools/findstring.sh
  tools/shell.sh
Labels: enhancement

#89 updating create tables script to include secondary index
  ci/v1/create_tables.py
Labels: bug

#90 updating README.md
  README.md
  loader/README.md
  s2/README.md
  s3/README.md
Labels: documentation

#91 updating README.md with prerequisites
  README.md
Labels: documentation

#92 Dkn4/ci
  README.md
  api-tpl.mak
  api.mak
Labels: documentation
